# This workflow will be run when an issue labeled "trigger-complete" is closed.

name: Participant completed course

# Trigger a workflow for a closed issue
on:
  issues:
    types: [closed]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Only run the job if the closed issue has the label "trigger-complete"
    # Idea borrowed from: https://github.community/t5/GitHub-Actions/Do-something-if-a-particular-label-is-set/td-p/40712
    if: contains(github.event.issue.labels.*.name, 'trigger-complete' )
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Seems like you need this first for all actions ...
      - name: Checkout repository
        uses: actions/checkout@v1
    
      # Replace the README with the course completion version
      - name: Update README.md
        run: |
          cat ./.github/commit_content/readme_participant_end.md > ./README.md
      
      # Updating a file uses the GitHub action, https://github.com/marketplace/actions/update-file-on-github
      - name: Commit updates to README.md
        uses: alexesprit/action-update-file@master
        with:
          file-path: ./README.md
          commit-msg: congratulations - you completed the course
          github-token: ${{ secrets.GITHUB_TOKEN }}
