# This workflow should be run once by starring the repo to create the needed issues.

name: Setup repo by creating issues

# Manually trigger this workflow for setting it up by clicking the star button. Only do this once.
# Borrowed from https://dev.to/s_abderemane/manual-trigger-with-github-actions-279e
on:
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Only allows repo owner to initiate
    if: github.actor == github.event.repository.owner.login

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Issue creation steps use GitHub action, https://github.com/marketplace/actions/create-issue-from-file
    steps:
      
      # Seems like you need this first for all actions ...
      - name: Checkout repository
        uses: actions/checkout@v1
    
      # Replace the README with the course startup version
      - name: Update README.md
        run: |
          cat ./.github/commit_content/readme_participant_start.md > ./README.md
      
      # Updating a file uses the GitHub action, https://github.com/marketplace/actions/update-file-on-github
      - name: Commit updates to README.md
        uses: alexesprit/action-update-file@master
        with:
          file-path: ./README.md
          commit-msg: instructions for starting the course
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
      #- name: Issue 1
      #  uses: peter-evans/create-issue-from-file@v2
      #  with:
      #    title: How to start working on a new project
      #    content-filepath: ./.github/issues_to_create/issue_01.md
      
      # A bunch more need to go here
      
      - name: Issue 9
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Closing the loop
          content-filepath: ./.github/issues_to_create/issue_09.md
          labels: trigger-collab
          
      #- name: Issue 10
      #  uses: peter-evans/create-issue-from-file@v2
      #  with:
      #    title: Get a collaborator's content locally
      #    content-filepath: ./.github/issues_to_create/issue_10.md
      
      - name: Issue 11
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Add two new sections of the story
          content-filepath: ./.github/issues_to_create/issue_11.md
          labels: trigger-conflict
      
      # A bunch of issues
      
      - name: Issue 17
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: In conclusion ...
          content-filepath: ./.github/issues_to_create/issue_17.md
          labels: trigger-complete
          
